opinio/config/routes.rb
Rails.application.routes.draw do
  post '/boy_requests/updateDelivery', :to => 'boy_requests#updateDelivery'  
  post '/delivery_requests/save', :to => 'delivery_requests#create'
  post '/boy_requests/save', :to => 'boy_requests#create'
  get '/delivery_requests/list', :to => 'delivery_requests#list'
  get '/boy_requests/list', :to => 'boy_requests#list'
  get '/boy_requests/createDeliveryItems', :to => 'boy_requests#createDeliveryItems'
  get '/acceptRequest', :to => 'app#pilot_app'  
  resources :boy_requests 
  resources :delivery_requests
  resources :stores
  resources :delivery_boys    
  resources :app
end

opinio/app/models/delivery_request.rb
class DeliveryRequest < ActiveRecord::Base
end

opinio/app/controllers/delivery_requests_controller.rb
class DeliveryRequestsController < ApplicationController
  before_action :set_delivery_request, only: [:show, :edit, :update, :destroy]

  def list                
    @requests = DeliveryRequest.find_by_sql("
      Select * FROM delivery_requests 
      where store_id = #{params[:store_id]}
      order by id DESC")
  end    

  # GET /delivery_requests
  # GET /delivery_requests.json
  def index
    @delivery_requests = DeliveryRequest.all
  end

  # GET /delivery_requests/1
  # GET /delivery_requests/1.json
  def show
  end

  # GET /delivery_requests/new
  def new
    @delivery_request = DeliveryRequest.new
  end

  # GET /delivery_requests/1/edit
  def edit
  end

  # POST /delivery_requests
  # POST /delivery_requests.json
  def create
    @delivery_request = DeliveryRequest.new(delivery_request_params)

    respond_to do |format|
      if @delivery_request.save
        format.html { redirect_to @delivery_request, notice: 'Delivery request was successfully created.' }
        format.json { render :show, status: :created, location: @delivery_request }
      else
        format.html { render :new }
        format.json { render json: @delivery_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /delivery_requests/1
  # PATCH/PUT /delivery_requests/1.json
  def update
    respond_to do |format|
      if @delivery_request.update(delivery_request_params)
        format.html { redirect_to @delivery_request, notice: 'Delivery request was successfully updated.' }
        format.json { render :show, status: :ok, location: @delivery_request }
      else
        format.html { render :edit }
        format.json { render json: @delivery_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /delivery_requests/1
  # DELETE /delivery_requests/1.json
  def destroy
    @delivery_request.destroy
    respond_to do |format|
      format.html { redirect_to delivery_requests_url, notice: 'Delivery request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_delivery_request
      @delivery_request = DeliveryRequest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def delivery_request_params
      params.require(:delivery_request).permit(:store_id, :request_time, :boys_required, :total_amount, :status, :accepted, :arrived, :on_route)
    end
end

opinio/app/helpers/delivery_requests_helper.rb
module DeliveryRequestsHelper
end

opinio/app/views/delivery_requests/_form.html.erb
<%= form_for(@delivery_request) do |f| %>
  <% if @delivery_request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@delivery_request.errors.count, "error") %> prohibited this delivery_request from being saved:</h2>

      <ul>
      <% @delivery_request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :store_id %><br>
    <%= f.number_field :store_id %>
  </div>
  <div class="field">
    <%= f.label :request_time %><br>
    <%= f.datetime_select :request_time %>
  </div>
  <div class="field">
    <%= f.label :boys_required %><br>
    <%= f.number_field :boys_required %>
  </div>
  <div class="field">
    <%= f.label :total_amount %><br>
    <%= f.text_field :total_amount %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :accepted %><br>
    <%= f.number_field :accepted %>
  </div>
  <div class="field">
    <%= f.label :arrived %><br>
    <%= f.number_field :arrived %>
  </div>
  <div class="field">
    <%= f.label :on_route %><br>
    <%= f.number_field :on_route %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

opinio/app/views/delivery_requests/edit.html.erb
<h1>Editing Delivery Request</h1>

<%= render 'form' %>

<%= link_to 'Show', @delivery_request %> |
<%= link_to 'Back', delivery_requests_path %>

opinio/app/views/delivery_requests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Delivery Requests</h1>

<table>
  <thead>
    <tr>
      <th>Store</th>
      <th>Request time</th>
      <th>Boys required</th>
      <th>Total amount</th>
      <th>Status</th>
      <th>Accepted</th>
      <th>Arrived</th>
      <th>On route</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @delivery_requests.each do |delivery_request| %>
      <tr>
        <td><%= delivery_request.store_id %></td>
        <td><%= delivery_request.request_time %></td>
        <td><%= delivery_request.boys_required %></td>
        <td><%= delivery_request.total_amount %></td>
        <td><%= delivery_request.status %></td>
        <td><%= delivery_request.accepted %></td>
        <td><%= delivery_request.arrived %></td>
        <td><%= delivery_request.on_route %></td>
        <td><%= link_to 'Show', delivery_request %></td>
        <td><%= link_to 'Edit', edit_delivery_request_path(delivery_request) %></td>
        <td><%= link_to 'Destroy', delivery_request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Delivery request', new_delivery_request_path %>

opinio/app/views/delivery_requests/list.html.erb
<% if @requests.blank? %>
<% else %>
<div id ="tab_b_request_list">
  <% @requests.each do |request| %>
  
  <div class="panel panel-default col-md-12 track_request_heading track_request" >
              <div class = "col-md-4 track_request_heading_item">
                Id - <%= request.id %>
              </div>
              <div class = "col-md-4 track_request_heading_item">
                Time - <%= request.request_time%>
              </div>
              <div class = "col-md-4 track_request_heading_item">               
                <div class="dropdown">
                  <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                    Status
                    <span class="caret"></span>
                  </button>
                  <ul class="dropdown-menu" aria-labelledby="dropdownMenu1" id = "request_delivery_status">                    
                    <li><a href="#">Pending</a></li>
                    <li><a href="#">Completed</a></li>                    
                  </ul>
                </div>
              </div>
            </div>   
            <div class="panel panel-default col-md-12 track_request track_request_content">
                <div class = "col-md-3 track_request_heading_item">
                Boys needed<br>
                <span class="glyphicon glyphicon-user"></span>&nbsp;<%= request.boys_required %>
              </div>
              <div class = "col-md-3 track_request_heading_item">
                Accepted<br>
                <span class="glyphicon glyphicon-ok"></span>&nbsp;<%= request.accepted %>
              </div>
               <div class = "col-md-3 track_request_heading_item">
                Arrived<br>
                <span class="glyphicon glyphicon-pushpin"></span>&nbsp;<%= request.arrived %>
              </div>
              <div class = "col-md-3 track_request_heading_item">
                On route<br>
                <span class="glyphicon glyphicon-thumbs-up"></span>&nbsp;<%= request.on_route %>
              </div>
             </div> 
             <div id = "request_id_<%= request.id %>" class="boys_detail_container">
             </div>

  <% end %>

</div>
<% end %>



 

opinio/app/views/delivery_requests/new.html.erb
<h1>New Delivery Request</h1>

<%= render 'form' %>

<%= link_to 'Back', delivery_requests_path %>

opinio/app/views/delivery_requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Store:</strong>
  <%= @delivery_request.store_id %>
</p>

<p>
  <strong>Request time:</strong>
  <%= @delivery_request.request_time %>
</p>

<p>
  <strong>Boys required:</strong>
  <%= @delivery_request.boys_required %>
</p>

<p>
  <strong>Total amount:</strong>
  <%= @delivery_request.total_amount %>
</p>

<p>
  <strong>Status:</strong>
  <%= @delivery_request.status %>
</p>

<p>
  <strong>Accepted:</strong>
  <%= @delivery_request.accepted %>
</p>

<p>
  <strong>Arrived:</strong>
  <%= @delivery_request.arrived %>
</p>

<p>
  <strong>On route:</strong>
  <%= @delivery_request.on_route %>
</p>

<%= link_to 'Edit', edit_delivery_request_path(@delivery_request) %> |
<%= link_to 'Back', delivery_requests_path %>