opinio/config/routes.rb
Rails.application.routes.draw do
  post '/boy_requests/updateDelivery', :to => 'boy_requests#updateDelivery'  
  post '/delivery_requests/save', :to => 'delivery_requests#create'
  post '/boy_requests/save', :to => 'boy_requests#create'
  get '/delivery_requests/list', :to => 'delivery_requests#list'
  get '/boy_requests/list', :to => 'boy_requests#list'
  get '/boy_requests/createDeliveryItems', :to => 'boy_requests#createDeliveryItems'
  get '/acceptRequest', :to => 'app#pilot_app'  
  resources :boy_requests 
  resources :delivery_requests
  resources :stores
  resources :delivery_boys    
  resources :app
end

opinio/app/models/boy_request.rb
class BoyRequest < ActiveRecord::Base
end

opinio/app/controllers/boy_requests_controller.rb
class BoyRequestsController < ApplicationController
  before_action :set_boy_request, only: [:show, :edit, :update, :destroy]

  def list                
    @requests = BoyRequest.find_by_sql("
      Select t1.id, t1.boy_id, t1.request_id, t2.name, t2.mobile, t1.eta, t1.request_status, t1.order_id, t1.delivery_destination FROM boy_requests t1
      INNER JOIN delivery_boys t2
      ON t1.boy_id = t2.id
      where store_id = #{params[:store_id]}
      order by boy_id")


  end   

  # GET /boy_requests
  # GET /boy_requests.json
  def index
    @boy_requests = BoyRequest.all
  end

  # GET /boy_requests/1
  # GET /boy_requests/1.json
  def show
  end

  # GET /boy_requests/new
  def new
    @boy_request = BoyRequest.new
  end

  # GET /boy_requests/1/edit
  def edit
  end

  # POST /boy_requests
  # POST /boy_requests.json
  def create
    @boy_request = BoyRequest.new(boy_request_params)    
    respond_to do |format|
      if @boy_request.save
        format.html { redirect_to @boy_request, notice: 'Boy request was successfully created.' }
        format.json { render :show, status: :created, location: @boy_request }
        a = DeliveryRequest.find(params["boy_request"]["request_id"])
        a.accepted = a.accepted + 1
        a.on_route = a.on_route + 1
        a.save
      else
        format.html { render :new }
        format.json { render json: @boy_request.errors, status: :unprocessable_entity }
      end
    end        
    
  end

  def updateDelivery    
    updateRecord = BoyRequest.find(params["updateDelivery"]["id"])
    updateRecord.order_id = params["updateDelivery"]["order_id"]
    updateRecord.delivery_destination = params["updateDelivery"]["delivery_destination"]
    updateRecord.delivery_lat = params["updateDelivery"]["delivery_lat"]
    updateRecord.delivery_lng = params["updateDelivery"]["delivery_lng"]
    updateRecord.delivery_start_time = params["updateDelivery"]["delivery_start_time"];
    updateRecord.save    
  end
   
  def createDeliveryItems
     @deliveries = BoyRequest.find_by_sql("
      Select t1.id, t1.boy_id, t1.request_id, t2.name, t2.mobile, t1.eta, t1.etd, t1.delivery_status, t1.order_id, t1.delivery_destination, t1.delivery_start_time, t1.delivery_lng, t1.delivery_lat, t1.order_id FROM boy_requests t1
      INNER JOIN delivery_boys t2
      ON t1.boy_id = t2.id
      where store_id = #{params[:store_id]}
      order by t1.order_id DESC")     
  end 

  # PATCH/PUT /boy_requests/1
  # PATCH/PUT /boy_requests/1.json
  def update    
    respond_to do |format|
      if @boy_request.update(boy_request_params)
        format.html { redirect_to @boy_request, notice: 'Boy request was successfully updated.' }
        format.json { render :show, status: :ok, location: @boy_request }
        a = DeliveryRequest.find(params["boy_request"]["request_id"])
        if params["boy_request"]["request_status"]  == "Arrived"        
          if a.arrived < a.boys_required
            a.arrived = a.arrived + 1
            a.on_route = a.on_route - 1
          end            
          a.save
        end          
      else
        format.html { render :edit }
        format.json { render json: @boy_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boy_requests/1
  # DELETE /boy_requests/1.json
  def destroy
    @boy_request.destroy
    respond_to do |format|
      format.html { redirect_to boy_requests_url, notice: 'Boy request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_boy_request
      @boy_request = BoyRequest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def boy_request_params
      params.require(:boy_request).permit(:boy_id, :request_id, :eta, :request_status, :order_id, :delivery_start_time, :delivery_destination, :delivery_status, :store_id, :delivery_lat, :delivery_lng)
    end
end

opinio/app/helpers/boy_requests_helper.rb
module BoyRequestsHelper
end

opinio/app/views/boy_requests/_form.html.erb
<%= form_for(@boy_request) do |f| %>
  <% if @boy_request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@boy_request.errors.count, "error") %> prohibited this boy_request from being saved:</h2>

      <ul>
      <% @boy_request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :boy_id %><br>
    <%= f.number_field :boy_id %>
  </div>
  <div class="field">
    <%= f.label :request_id %><br>
    <%= f.number_field :request_id %>
  </div>
  <div class="field">
    <%= f.label :store_id %><br>
    <%= f.number_field :store_id %>
  </div>
  <div class="field">
    <%= f.label :eta %><br>
    <%= f.text_field :eta %>
  </div>
  <div class="field">
    <%= f.label :eta %><br>
    <%= f.text_field :etd %>
  </div>
  <div class="field">
    <%= f.label :request_status %><br>
    <%= f.text_field :request_status %>
  </div>
  <div class="field">
    <%= f.label :order_id %><br>
    <%= f.number_field :order_id %>
  </div>
  <div class="field">
    <%= f.label :delivery_start_time %><br>
    <%= f.text_field :delivery_start_time %>
  </div>
  <div class="field">
    <%= f.label :delivery_destination %><br>
    <%= f.text_area :delivery_destination %>
  </div>
  <div class="field">
    <%= f.label :delivery_status %><br>
    <%= f.text_field :delivery_status %>
  </div>
  <div class="field">
    <%= f.label :delivery_lat %><br>
    <%= f.text_area :delivery_lat %>
  </div>
  <div class="field">
    <%= f.label :delivery_lng %><br>
    <%= f.text_field :delivery_lng %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

opinio/app/views/boy_requests/createDeliveryItems.html.erb
<% if @deliveries.blank? %>
<% else %>
<div id ="tab_c_request_list">
  <% @deliveries.each do |request| %>  
<div class="panel panel-default col-md-12 track_request_heading track_request classHelper_2" id ="id_helper_<%=request.order_id %>_<%= request.boy_id %>">
              <div class = "col-md-4 track_request_heading_item" id = "delivery_order_id_<%=request.order_id %>_<%= request.boy_id %>">
                Order Id - <%= request.order_id %>
                <p style="display:none" id = "delivery_lat_<%=request.order_id %>_<%= request.boy_id %>"><%= request.delivery_lat %></p>
                <p style="display:none" id = "delivery_lng_<%=request.order_id %>_<%= request.boy_id %>"><%= request.delivery_lng %></p>
              </div>
              <div class = "col-md-4 track_request_heading_item" id = "delivery_start_time_<%=request.order_id %>_<%= request.boy_id %>">
                Delivery started - <%= request.delivery_start_time %>
              </div>
              <div class = "col-md-4 track_request_heading_item" id="delivery_status_<%=request.order_id %>_<%= request.boy_id %>">               
                <div class="dropdown">
                  <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                    Status
                    <span class="caret"></span>
                  </button>
                  <ul class="dropdown-menu" aria-labelledby="dropdownMenu2" id = "delivery_status">
                    <li><a href="#">On the way</a></li>
                    <li><a href="#">Reached</a></li>                    
                  </ul>
                </div>
              </div>
            </div>   
     
             <div class="panel panel-default col-md-12 track_request track_request_details" id = "driver_boy_<%= request.boy_id %>">
              <!-- <p>Delivery boys Details</p> -->
              <div class = "col-md-3 track_request_details_item" id = "delivery_name_<%=request.order_id %>_<%= request.boy_id %>">
                Name - <%= request.name %>
              </div>
              <div class = "col-md-3 track_request_details_item" id = "delivery_mobile_<%=request.order_id %>_<%= request.boy_id %>">
                Contact - <%= request.mobile %>
              </div>
                 <div class = "col-md-3 track_request_details_item" id = "delivery_etd_<%=request.order_id %>_<%= request.boy_id %>">
                ETD - <%= request.etd %>
              </div>
              <div class = "col-md-3 track_request_details_item" id = "delivery_status_<%=request.order_id %>_<%= request.boy_id %>">
                <% if request.delivery_status != "" %>
                <%= request.delivery_status %>
                <% else %>
                No Status
                <% end %>
              </div>
                             
              </div>    


             <% end %>
</div>
<% end %>
 

opinio/app/views/boy_requests/edit.html.erb
<h1>Editing Boy Request</h1>

<%= render 'form' %>

<%= link_to 'Show', @boy_request %> |
<%= link_to 'Back', boy_requests_path %>

opinio/app/views/boy_requests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Boy Requests</h1>

<table>
  <thead>
    <tr>
      <th>Boy</th>
      <th>Request</th>
      <th>Store</th>
      <th>Eta</th>
      <th>Request status</th>
      <th>Order</th>
      <th>Delivery start time</th>      
      <th>Delivery destination</th>
      <th>Delivery status</th>
      <th>Delivery Lat</th>
      <th>Delivery Long</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @boy_requests.each do |boy_request| %>
      <tr>
        <td><%= boy_request.boy_id %></td>
        <td><%= boy_request.request_id %></td>
        <td><%= boy_request.store_id %></td>
        <td><%= boy_request.eta %></td>
        <td><%= boy_request.request_status %></td>
        <td><%= boy_request.order_id %></td>
        <td><%= boy_request.delivery_start_time %></td>        
        <td><%= boy_request.delivery_destination %></td>
        <td><%= boy_request.delivery_status %></td>
        <td><%= boy_request.delivery_lat %></td>
        <td><%= boy_request.delivery_lng %></td>
        <td><%= link_to 'Show', boy_request %></td>
        <td><%= link_to 'Edit', edit_boy_request_path(boy_request) %></td>
        <td><%= link_to 'Destroy', boy_request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Boy request', new_boy_request_path %>

opinio/app/views/boy_requests/list.html.erb
<% if @requests.blank? %>
<% else %>

  <% @requests.each do |request| %>
  <div id ="request_id_<%= request.request_id %>" class="helperClass request_id_<%=request.request_id %>">  
    <div class="panel panel-default col-md-12 track_request track_request_details" id = "delivery_boy_<%= request.boy_id %>">
              <!-- <p>Delivery boys Details</p> -->
              <div class = "col-md-2 track_request_details_item" id = "boy_id_<%=request.request_id %>_<%= request.boy_id %>">
                Id - <%= request.boy_id %>
                <p style ="display : none" id = "id_<%=request.request_id %>_<%= request.boy_id %>"><%=request.id%></p>
                
              </div>
              <div class = "col-md-2 track_request_details_item" id = "name_<%=request.request_id %>_<%= request.boy_id %>" >
                Name - <%= request.name %>
              </div>
              <div class = "col-md-2 track_request_details_item" id = "mobile_<%=request.request_id %>_<%= request.boy_id %>">
                Contact - <%= request.mobile %>
              </div>
              <div class = "col-md-2 track_request_details_item" id = "eta_<%=request.request_id %>_<%= request.boy_id %>">
                <% if request.request_status == "Arrived"%>
                <% request.eta = 0%>                
                <%end%>
                ETA - <%= request.eta %>
              </div>
              <div class = "col-md-2 track_request_details_item" id = "request_status_<%=request.request_id %>_<%= request.boy_id %>">
                <%= request.request_status %>
              </div>
              <div class = "col-md-2 track_request_details_item">
                <button type="button" class="btn btn-primary" id="assign_delivery$<%=request.request_id %>_<%= request.boy_id %>" onclick="assignDelivery(this)" >Assign Delivery</button>
                &nbsp;<a class = "delivery_destination" data-toggle="collapse" aria-expanded="false" aria-controls="delivery_boy_<%=request.request_id %>_<%= request.boy_id %>" href="#delivery_boy_<%=request.request_id %>_<%= request.boy_id %>" id = "dropdown_anchor_<%=request.request_id %>_<%= request.boy_id %>"><i class="glyphicon glyphicon-arrow-down"></i></a>
              </div>    
              <div class="collapse col-md-12 delivery_destination_collpase" id="delivery_boy_<%=request.request_id %>_<%= request.boy_id %>">                
                <div class = "col-md-6 delivery_destination_collpase_item">
                    Customer order number - <span id = "collapse_item_order_<%=request.request_id %>_<%= request.boy_id %>"><%= request.order_id %></span>
                  </div>
                  <div class = "col-md-6 delivery_destination_collpase_item">
                    Delivery Location - <span id = "collapse_item_dest_<%=request.request_id %>_<%= request.boy_id %>"><%= request.delivery_destination %></span>
                  </div>                  
              </div>          
             </div>

  </div>
  <% end %>

<% end %>



 

 

opinio/app/views/boy_requests/new.html.erb
<h1>New Boy Request</h1>

<%= render 'form' %>

<%= link_to 'Back', boy_requests_path %>

opinio/app/views/boy_requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Boy:</strong>
  <%= @boy_request.boy_id %>
</p>

<p>
  <strong>Request:</strong>
  <%= @boy_request.request_id %>
</p>

<p>
  <strong>Store:</strong>
  <%= @boy_request.store_id %>
</p>

<p>
  <strong>Eta:</strong>
  <%= @boy_request.eta %>
</p>

<p>
  <strong>Etd:</strong>
  <%= @boy_request.etd %>
</p>

<p>
  <strong>Request status:</strong>
  <%= @boy_request.request_status %>
</p>

<p>
  <strong>Order:</strong>
  <%= @boy_request.order_id %>
</p>

<p>
  <strong>Delivery start time:</strong>
  <%= @boy_request.delivery_start_time %>
</p>


<p>
  <strong>Delivery destination:</strong>
  <%= @boy_request.delivery_destination %>
</p>

<p>
  <strong>Delivery status:</strong>
  <%= @boy_request.delivery_status %>
</p>

<p>
  <strong>Delivery lat:</strong>
  <%= @boy_request.delivery_lat %>
</p>

<p>
  <strong>Delivery long:</strong>
  <%= @boy_request.delivery_lng %>
</p>

<%= link_to 'Edit', edit_boy_request_path(@boy_request) %> |
<%= link_to 'Back', boy_requests_path %>