opinio/config/routes.rb
Rails.application.routes.draw do
  post '/boy_requests/updateDelivery', :to => 'boy_requests#updateDelivery'  
  post '/delivery_requests/save', :to => 'delivery_requests#create'
  post '/boy_requests/save', :to => 'boy_requests#create'
  get '/delivery_requests/list', :to => 'delivery_requests#list'
  get '/boy_requests/list', :to => 'boy_requests#list'
  get '/boy_requests/createDeliveryItems', :to => 'boy_requests#createDeliveryItems'
  get '/acceptRequest', :to => 'app#pilot_app'  
  resources :boy_requests 
  resources :delivery_requests
  resources :stores
  resources :delivery_boys    
  resources :app
end

opinio/app/models/delivery_boy.rb
class DeliveryBoy < ActiveRecord::Base
end

opinio/app/controllers/delivery_boys_controller.rb
class DeliveryBoysController < ApplicationController
  before_action :set_delivery_boy, only: [:show, :edit, :update, :destroy]

  # GET /delivery_boys
  # GET /delivery_boys.json
  def index
    @delivery_boys = DeliveryBoy.all
  end

  # GET /delivery_boys/1
  # GET /delivery_boys/1.json
  def show
  end

  # GET /delivery_boys/new
  def new
    @delivery_boy = DeliveryBoy.new
  end

  # GET /delivery_boys/1/edit
  def edit
  end

  # POST /delivery_boys
  # POST /delivery_boys.json
  def create
    @delivery_boy = DeliveryBoy.new(delivery_boy_params)

    respond_to do |format|
      if @delivery_boy.save
        format.html { redirect_to @delivery_boy, notice: 'Delivery boy was successfully created.' }
        format.json { render :show, status: :created, location: @delivery_boy }
      else
        format.html { render :new }
        format.json { render json: @delivery_boy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /delivery_boys/1
  # PATCH/PUT /delivery_boys/1.json
  def update
    respond_to do |format|
      if @delivery_boy.update(delivery_boy_params)
        format.html { redirect_to @delivery_boy, notice: 'Delivery boy was successfully updated.' }
        format.json { render :show, status: :ok, location: @delivery_boy }
      else
        format.html { render :edit }
        format.json { render json: @delivery_boy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /delivery_boys/1
  # DELETE /delivery_boys/1.json
  def destroy
    @delivery_boy.destroy
    respond_to do |format|
      format.html { redirect_to delivery_boys_url, notice: 'Delivery boy was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_delivery_boy
      @delivery_boy = DeliveryBoy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def delivery_boy_params
      params.require(:delivery_boy).permit(:name, :mobile)
    end
end

opinio/app/helpers/delivery_boys_helper.rb
module DeliveryBoysHelper
end

opinio/app/views/delivery_boys/_form.html.erb
<%= form_for(@delivery_boy) do |f| %>
  <% if @delivery_boy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@delivery_boy.errors.count, "error") %> prohibited this delivery_boy from being saved:</h2>

      <ul>
      <% @delivery_boy.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :mobile %><br>
    <%= f.text_field :mobile %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

opinio/app/views/delivery_boys/edit.html.erb
<h1>Editing Delivery Boy</h1>

<%= render 'form' %>

<%= link_to 'Show', @delivery_boy %> |
<%= link_to 'Back', delivery_boys_path %>

opinio/app/views/delivery_boys/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Delivery Boys</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Mobile</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @delivery_boys.each do |delivery_boy| %>
      <tr>
        <td><%= delivery_boy.name %></td>
        <td><%= delivery_boy.mobile %></td>
        <td><%= link_to 'Show', delivery_boy %></td>
        <td><%= link_to 'Edit', edit_delivery_boy_path(delivery_boy) %></td>
        <td><%= link_to 'Destroy', delivery_boy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Delivery boy', new_delivery_boy_path %>

opinio/app/views/delivery_boys/new.html.erb
<h1>New Delivery Boy</h1>

<%= render 'form' %>

<%= link_to 'Back', delivery_boys_path %>

opinio/app/views/delivery_boys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @delivery_boy.name %>
</p>

<p>
  <strong>Mobile:</strong>
  <%= @delivery_boy.mobile %>
</p>

<%= link_to 'Edit', edit_delivery_boy_path(@delivery_boy) %> |
<%= link_to 'Back', delivery_boys_path %>