opinio/config/routes.rb
Rails.application.routes.draw do
  post '/boy_requests/updateDelivery', :to => 'boy_requests#updateDelivery'  
  post '/delivery_requests/save', :to => 'delivery_requests#create'
  post '/boy_requests/save', :to => 'boy_requests#create'
  get '/delivery_requests/list', :to => 'delivery_requests#list'
  get '/boy_requests/list', :to => 'boy_requests#list'
  get '/boy_requests/createDeliveryItems', :to => 'boy_requests#createDeliveryItems'
  get '/acceptRequest', :to => 'app#pilot_app'  
  resources :boy_requests 
  resources :delivery_requests
  resources :stores
  resources :delivery_boys    
  resources :app
end

opinio/app/models/store.rb
class Store < ActiveRecord::Base
end

opinio/app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show, :edit, :update, :destroy]

  # GET /stores
  # GET /stores.json
  def index
    @stores = Store.all
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: 'Store was successfully created.' }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: 'Store was successfully updated.' }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url, notice: 'Store was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def store_params
      params.require(:store).permit(:name, :address, :lat, :long, :contact_person, :mobile)
    end
end

opinio/app/helpers/stores_helper.rb
module StoresHelper
end

opinio/app/views/stores/_form.html.erb
<%= form_for(@store) do |f| %>
  <% if @store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
      <% @store.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :lat %><br>
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :long %><br>
    <%= f.text_field :long %>
  </div>
  <div class="field">
    <%= f.label :contact_person %><br>
    <%= f.text_field :contact_person %>
  </div>
  <div class="field">
    <%= f.label :mobile %><br>
    <%= f.text_field :mobile %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

opinio/app/views/stores/edit.html.erb
<h1>Editing Store</h1>

<%= render 'form' %>

<%= link_to 'Show', @store %> |
<%= link_to 'Back', stores_path %>

opinio/app/views/stores/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Stores</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Lat</th>
      <th>Long</th>
      <th>Contact person</th>
      <th>Mobile</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stores.each do |store| %>
      <tr>
        <td><%= store.name %></td>
        <td><%= store.address %></td>
        <td><%= store.lat %></td>
        <td><%= store.long %></td>
        <td><%= store.contact_person %></td>
        <td><%= store.mobile %></td>
        <td><%= link_to 'Show', store %></td>
        <td><%= link_to 'Edit', edit_store_path(store) %></td>
        <td><%= link_to 'Destroy', store, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Store', new_store_path %>

opinio/app/views/stores/new.html.erb
<h1>New Store</h1>

<%= render 'form' %>

<%= link_to 'Back', stores_path %>

opinio/app/views/stores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @store.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @store.address %>
</p>

<p>
  <strong>Lat:</strong>
  <%= @store.lat %>
</p>

<p>
  <strong>Long:</strong>
  <%= @store.long %>
</p>

<p>
  <strong>Contact person:</strong>
  <%= @store.contact_person %>
</p>

<p>
  <strong>Mobile:</strong>
  <%= @store.mobile %>
</p>

<%= link_to 'Edit', edit_store_path(@store) %> |
<%= link_to 'Back', stores_path %>